[project]
name = "vvm-demo-digital-smart-doctor-agent"
version = "0.1.0"
description = "Add your description here"
requires-python = "==3.12.*"
dependencies = [
    "aiomysql==0.2.0",
    "beautifulsoup4>=4.11.0",
    "dashscope==1.23.2",
    "duckduckgo-search>=3.9.0",
    "langchain==0.3.24",
    "langchain-community==0.3.23",
    "langchain-milvus==0.1.6",
    "langchain-openai==0.3.24",
    "langgraph==0.4.8",
    "langgraph-checkpoint-mysql==2.0.15",
    "nltk==3.9.2",
    "numpy==2.2.5",
    "openpyxl==3.1.5",
    "peft==0.17.1",
    "pydantic-settings==2.9.1",
    "pymilvus==2.5.8",
    "pymysql==1.1.1",
    "pyyaml==6.0.3",
    "requests>=2.32.5",
    "tavily-python>=0.3.0",
    "ultralytics==8.4.6",
    "opencv-python>=4.6.0",
    "Pillow>=7.1.2",
    "loguru>=0.7.3",
    "prompt-toolkit>=3.0.0",
    "rich>=13.0.0",
    "python-multipart>=0.0.9",
]
